//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18052
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication5.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISource")]
    public interface ISource {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISource/UploadFile", ReplyAction="http://tempuri.org/ISource/UploadFileResponse")]
        bool UploadFile(System.IO.MemoryStream ms, string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISource/UploadFile", ReplyAction="http://tempuri.org/ISource/UploadFileResponse")]
        System.Threading.Tasks.Task<bool> UploadFileAsync(System.IO.MemoryStream ms, string filename);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISourceChannel : ConsoleApplication5.ServiceReference1.ISource, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SourceClient : System.ServiceModel.ClientBase<ConsoleApplication5.ServiceReference1.ISource>, ConsoleApplication5.ServiceReference1.ISource {
        
        public SourceClient() {
        }
        
        public SourceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SourceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SourceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SourceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UploadFile(System.IO.MemoryStream ms, string filename) {
            return base.Channel.UploadFile(ms, filename);
        }
        
        public System.Threading.Tasks.Task<bool> UploadFileAsync(System.IO.MemoryStream ms, string filename) {
            return base.Channel.UploadFileAsync(ms, filename);
        }
    }
}
